name: Mirror to Gitlab

on: [push, delete]

jobs:
  gitlab:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          lkurz@ssh://git@bitbucket.hdfgroup.org:7999/~lkurz/mirror-test.git
        ssh_private_key:
          ${{ secrets. }}
