name: Mirror to BBKT mirror-test

on: [push, delete]

jobs:
  bbkt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: lkurz/mirror-action@master
      with:
        REMOTE: ${{ secrets.GIT_MIRROR_BBKT }}
        GIT_USERNAME: ${{ secrets.GIT_USER }}
        GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
    
