name: Mirror to BBKT mirror-test

on: [push, delete]

jobs:
  bbkt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: spyoungtech/mirror-action@master
      with:
        REMOTE: 'https://bitbucket.hdfgroup.org/~lkurz/mirror-test.git'
        GIT_USERNAME: kurz
        GIT_PASSWORD: ${{ secrets.BBKT_MIRRO }}
    
